import * as Crypto from 'expo-crypto';
import * as SecureStore from 'expo-secure-store';

/**
 * A stable identifier for this installation, used for anonymous sign-in.
 *
 * Generated by us and stored, rather than read from the device.
 * `Application.getIosIdForVendorAsync()` and Android's ID both change in ways that would
 * silently strand a user's data: reinstalling the last app from a vendor resets the iOS
 * one, and factory reset or a different signing key resets the Android one. Neither is
 * meant as a user identifier, and both are increasingly restricted.
 *
 * Kept in SecureStore so it survives an app update and stays out of plain backups.
 * Uninstalling loses it, which is correct: an anonymous account is tied to an install, and
 * that is exactly why linking it to a real account matters.
 */
const KEY = 'device-id';

export async function deviceId(): Promise<string> {
  const existing = await SecureStore.getItemAsync(KEY);
  if (existing) {
    return existing;
  }
  const generated = Crypto.randomUUID();
  await SecureStore.setItemAsync(KEY, generated);
  return generated;
}
